name: Compile and Unit Test

on: [push, pull_request]

jobs:
  ppr-api-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        working-directory: ppr-api
        run: |
          python -m pip install --index-url $index_url --upgrade pip
          pip install --index-url $index_url -r requirements/dev.txt
      - name: Lint non-test Source
        working-directory: ppr-api
        run: |
          pylint -E src
          flake8 src
      - name: Execute Unit Tests with PyTest
        working-directory: ppr-api
        run: |
          pip install .
          pytest
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          flags: python_unittests
          fail_ci_if_error: false

  ims-api-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Compile and execute tests
        working-directory: ims-api
        run: |
          ./gradlew test

  ppr-ui-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - run: npm ci
        working-directory: ppr-ui
      - run: npm run lint -- --no-fix
        working-directory: ppr-ui
      - run: npm run test:unit:cov
        working-directory: ppr-ui
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          fail_ci_if_error: false
